po/zh_CN.po, po/zh_TW.po
Update Chinese translation files. Thanks.
=> Update Chinese translation

po/zh_CN.po, po/zh_TW.po
=> Update Chinese translation files

po/ru.po
=> Updated RU.po

src/extension.js
When working offline, I rather would have a loading icon instead of 'Loading weather ...' info text. Just a small annoyance.
=> Remove 'Loading weather ...' placeholder text.

po/zh_CN.po, po/zh_TW.po
=> Update Chinese translation files.

po/LINGUAS, po/id.po
have been used extension for several years and realised that it has no Indonesian translation yet. So, I decided to initiate one.
=> Indonesian translation

po/it.po
Hi,
I've fixed some bad-translated entries and finished translating what was left undone.
=> Update Italian translation (100%)

data/weather-settings.ui, po/LINGUAS, po/ar.po, src/extension.js, src/forecast_io.js, src/openweathermap_org.js
Add Arabic translation and mark few required strings translatable.
=> Arabic translation

po/ca.po
=> updated catalan translation

po/POTFILES.in, po/fr.po, po/gnome-shell-extension-openweather.pot
These commits fix a translation error in French language, fix the generation of the .pot and .po files using make gnome-shell-extension-openweather.pot and make update-po.
I also have refreshed the gnome-shell-extension-openweather.pot file
=> Some translation related updates

po/cs.po
Including check of consistency and minor changes according to official translation of Beaufort scale and weather conditions
=> Update of czech transtation in current version of the extension

po/fr.po, po/gnome-shell-extension-openweather.pot
- remove #,fuzzy tag on previous modifications (notably plural forms)
- nuke real fuzzy garbage
- uncapitalize day names
- typo: extention → extension
- other small fixes (units…)
=> More French fixes

po/pt_BR.po
Hello jens, the pt_BR.po file has been updated, the old file contained some fuzzi strings
=> Updade pt_BR.po file

po/cs.po
Fixed one bad weather condition name and translated strings related to the new menu-box positioning feature.
=> CS translation

po/zh_CN.po, po/zh_TW.po
=> Update Chinese translates.

README.md
Adding instructions on how to install this package from the Arch User Repository.
=> Adding instructions on how to install on Arch Linux using AUR

po/pt_BR.po
pt-BR translation, fix translate of Humidity
=> pt-BR translation, fix translate of Humidity

po/ca.po
Xàfecs de gran intessitat > Xàfecs de gran intensitat
=> Little misspelling in line 469

po/pt_BR.po
Hi @jenslody, Brazilian Portuguese translation updated, thanks for this extension
=> Update pt_BR.po file

po/cs.po
To keep up with other transtations, weather conditions switched to Caps...
=> Capitalize weather conditions in Czech translation

po/sr.po, po/sr@latin.po
=> Update Serbian translation (sr and sr@latin)

po/fi.po
Updated the sometimes robotic and a bit funny Finnish translation.
=> Copyedited Finnish translation

po/uk.po
Added new translation in Ukrainian language.
=> New translation in Ukrainian
